Development 1.2 (#6)
* Version 1.1 Adds support for Installer Product (#3)

* Fix typo in README.md.  Update the POM to version 1.1 which will morph this into something that can work with the AtScale Installer Version

* Since we cannot download the correct hive driver from MavenCentral we add it to the project under a /lib directory

* We add the jar that is in the lib directory to the pom.xml

* Milestone initial support for AtScale Installer version ability to pull queries from the atscale postgres database ability to use the Hive endpoint to query AtScale

* Updates the query that pulls queries from the atscale postgres database per feedback from Dave

* Fix an error that resulted in mangling non hive JDBC URL's such that connections failed.

* Milestone, now support Installer XMLA tests

* Improve ability to control tests via parameters

* Parameterized <UseAggregates>,<GenerateAggregate,<UseQueryCache>, and <UseAggregateCache> properties for XMLA calls so they can now be set in the properties file.

* Improves logging

* Have to alter the way we make the Hive Driver available.  The prior way was interfering with dependency resolution in the atscale-gatling project.  We now run the ConfigurationExecutor class to install this dependency into the local maven repository.

* Adding executors that demonstrate getting this to work with Installer.

* Had to delete the ConfigurationExecutor the defined dependency in the POM prevents the class from compiling if it's not there and the point of this class was to help put it there.  Yea, that was not my most clever moment.  We add an execution command to the pom.xml to facilitate running the query extractor for the installer, we align the README.md file to the changes.

* Improves README.md

---------

Co-authored-by: stevehall <steve.hall@atscale.com>

* Atscale 41101 (#4)

* Fix typo in README.md.  Update the POM to version 1.1 which will morph this into something that can work with the AtScale Installer Version

* Since we cannot download the correct hive driver from MavenCentral we add it to the project under a /lib directory

* We add the jar that is in the lib directory to the pom.xml

* Milestone initial support for AtScale Installer version ability to pull queries from the atscale postgres database ability to use the Hive endpoint to query AtScale

* Updates the query that pulls queries from the atscale postgres database per feedback from Dave

* Fix an error that resulted in mangling non hive JDBC URL's such that connections failed.

* Milestone, now support Installer XMLA tests

* Improve ability to control tests via parameters

* Parameterized <UseAggregates>,<GenerateAggregate,<UseQueryCache>, and <UseAggregateCache> properties for XMLA calls so they can now be set in the properties file.

* Improves logging

* Have to alter the way we make the Hive Driver available.  The prior way was interfering with dependency resolution in the atscale-gatling project.  We now run the ConfigurationExecutor class to install this dependency into the local maven repository.

* Adding executors that demonstrate getting this to work with Installer.

* Had to delete the ConfigurationExecutor the defined dependency in the POM prevents the class from compiling if it's not there and the point of this class was to help put it there.  Yea, that was not my most clever moment.  We add an execution command to the pom.xml to facilitate running the query extractor for the installer, we align the README.md file to the changes.

* Improves README.md

* AtScale-41101 Implements ability to specify log file names and whether to append or overwrite log file contents on each successive run.  Must make compatible changes to the atscale-gatling project.  We changed the logging framework and will need to make the similar changes in that project.

* Removes System.out.println caught by the Copilot code review

* Code improvements per Copilot code review. Removes duplicate code, improves consistency in the example executors, stops logging the first few characters of the Bearer token.

---------

Co-authored-by: stevehall <steve.hall@atscale.com>

* Alters logging of XML payloads large XML payloads consume too much heap capacity.  Adds clarity around testing of Installer (#5)

authored-by: stevehall <steve.hall@atscale.com>

* Adding initial support for Windows development

* Modifies for version 1,2, modifies the logging file to increase the queue size a bit, changes SimulationExecutor to work with Windows.

* Moves to using Java java.nio.file.Paths so that we can be indifferent to which operating system we are running on.

* Adds support for development on Windows.

* Ignore user generated properties files

* ATSCALE-41191 Ability to run executors sequentially or concurrently, ATSCALE-41151

* Address the java.lang.NoClassDefFoundError I noticed at the end of each executor run.

* This change shuts down the logging system and stops any additional logging to better address the java.lang.NoClassDefFoundError I noticed at the end of each executor run.  That issue is corrected by shutting down the logger then deleting empty log files.

* Update src/main/com/atscale/java/utils/QueryHistoryFileUtil.java

Fix typo

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update src/main/com/atscale/java/jdbc/simulations/AtScaleOpenInjectionStepSimulation.java

Remove duplicate logging statements

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update pom.xml

remove second classpathScope only one is supported

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Fix typo in constant

* Consistency improvement

* Consistency improvement and alignment with code review suggestion

* Consistency improvement and alignment with code review suggestion

* Consistency improvement and alignment with code review suggestion

* Consistency improvement and alignment with code review suggestion

* Consistency improvement and alignment with code review suggestion

* Consistency improvement and alignment with code review suggestion

* Update src/main/com/atscale/java/executors/SequentialSimulationExecutor.java

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

---------

Co-authored-by: stevehall <steve.hall@atscale.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>